Use OnlineShopping;

Insert Into City Values('Karachi')
Insert Into City Values('Lahore')
Insert Into City Values('Faisalabad')
Insert Into City Values('Rawalpindi')
Insert Into City Values('Gujranwala')
Insert Into City Values('Peshawar')
Insert Into City Values('Multan')
Insert Into City Values('Hyderabad')
Insert Into City Values('Islamabad')
Insert Into City Values('Quetta')
Insert Into City Values('Bahawalpur')
Insert Into City Values('Sargodha')
Insert Into City Values('Sialkot')
Insert Into City Values('Sukkur')
Insert Into City Values('Jhang')
Insert Into City Values('Larkana')
Insert Into City Values('Dera Ghazi Khan')
Insert Into City Values('Shekhupura')
Insert Into City Values('Kasur')
Insert Into City Values('Rahim Yar Khan')
Insert Into City Values('Gujrat')
Insert Into City Values('Mardan')
Insert Into City Values('Sahiwal')
Insert Into City Values('Okara')
Insert Into City Values('Wah Cantonment')
Insert Into City Values('Mingora')
Insert Into City Values('Mirpur Khas')
Insert Into City Values('Chiniot')
Insert Into City Values('Nawabshah')
Insert Into City Values('Kāmoke')
Insert Into City Values('Burewala')
Insert Into City Values('Jhelum')
Insert Into City Values('Sadiqabad')
Insert Into City Values('Khanewal')
Insert Into City Values('Hafizabad')
Insert Into City Values('Kohat')
Insert Into City Values('Jacobabad')
Insert Into City Values('Shikarpur')
Insert Into City Values('Muzaffargarh')
Insert Into City Values('Khanpur')
Insert Into City Values('Gojra')
Insert Into City Values('Bahawalnagar')
Insert Into City Values('Abbottabad')
Insert Into City Values('Muridke')
Insert Into City Values('Pakpattan')
Insert Into City Values('Khuzdar')
Insert Into City Values('Jaranwala')
Insert Into City Values('Chishtian')
Insert Into City Values('Daska')
Insert Into City Values('Bhalwal')
Insert Into City Values('Mandi Bahauddin')
Insert Into City Values('Ahmadpur East')
Insert Into City Values('Kamalia')
Insert Into City Values('Tando Adam')
Insert Into City Values('Khairpur')
Insert Into City Values('Dera Ismail Khan')
Insert Into City Values('Vehari')
Insert Into City Values('Nowshera')
Insert Into City Values('Dadu')
Insert Into City Values('Wazirabad')
Insert Into City Values('Khushab')
Insert Into City Values('Charsada')
Insert Into City Values('Swabi')
Insert Into City Values('Chakwal')
Insert Into City Values('Mianwali')
Insert Into City Values('Tando Allahyar')
Insert Into City Values('Kot Adu')
Insert Into City Values('Turbat')
