Use OnlineShopping;

Insert Into Product Values('Air Mouse C120 for Android and Smart TV','1')
Insert Into Product Values('Air Mouse MX3 for Android and Smart TV','1')
Insert Into Product Values('MINI TOUCH PAD RF 500 WIRELESS WITH 3 COLOUR BACKLIGHT','1')
Insert Into Product Values('Viboton Touch pad wireless keyboard mouse S1','1')
Insert Into Product Values('Android Hdmi Dongle Quad Core TV Stick 2G+8G MK809III','1')
Insert Into Product Values('ANDROID SMART TV BOX MXQ 4K QUAD CORE 1G+8G','1')
Insert Into Product Values('ANDROID TV BOX MXQ PRO 4K QUAD CORE 2.0GHZ 1GB+8GB','1')
Insert Into Product Values('Android Smart TV Box NexBox A95X R1 Quad-core 1G+8G Android 7.1.2','1')
Insert Into Product Values('ANDRIOD TV BOX H96 PRO PLUS 3GB+32GB OCTA CORE 4K ULTA HD TV 7.1v','1')
Insert Into Product Values('ANDRIOD TV BOX H96 MAX 4GB+32GB 4K OCTA CORE','1')
Insert Into Product Values('Android Smart TV Box X96 mini Quad Core 2g+16g','1')
Insert Into Product Values('MECOOL KIII PRO ANDRIOD TV  OCTA CORE 3GB RAM 16GB ROM DVB-T2 +S2','1')
Insert Into Product Values('AIR MOUSE JS6/T6 KEYBOARD WITH TOUCH PAD','1')
Insert Into Product Values('Android Smart TV Box V88 Piano Quad Core 4GB+16GB','1')
Insert Into Product Values('Air Mouse MX3 Backlit For Android And Smart Tv','1')
Insert Into Product Values('ANDRIOD TV BOX H96MAX H2 4GB+32GB QUAD CONRE 4K ULTA HD TV 7.1.2V','1')
Insert Into Product Values('Digital Persona Finger Print Reader URU 4500','2')
Insert Into Product Values('ZKTECO I face 702 advance machine','2')
Insert Into Product Values('ZKTECO TX628 attendance machine','2')
Insert Into Product Values('ZKTECO live 20R usb figerprint reader','2')
Insert Into Product Values('ZKTECO K4500 USB FINGERPRINT READER','2')
Insert Into Product Values('ZKTECO TX628 with RFID card attendance machine','2')
Insert Into Product Values('I face 702 Battery ','2')
Insert Into Product Values('DIGITAL PERSONA FINGERPRINT READER URU 5100','2')
Insert Into Product Values('Barcode Bluetooth Scanner Speed-X 3100','3')
Insert Into Product Values('Barcode Handy Scanner 2D Speed-X 6100','3')
Insert Into Product Values('Barcode Desktop Scanner 2D Speed-X 9200','3')
Insert Into Product Values('Barcode Desktop Scanner Speed-x 9100','3')
Insert Into Product Values('Barcode Scanner auto scan Speed-X 8100','3')
Insert Into Product Values('Barcode Scanner Speed-X 8200','3')
Insert Into Product Values('Barcode Scanner Wifi Speed-X 5100','3')
Insert Into Product Values('Speed-X 300 Thermal Receipt Printer USB+RS232+LAN','3')
Insert Into Product Values('Speed-X 200 Thermal Receipt Printer USB+RS232','3')
Insert Into Product Values('Thermal Printer Main Board PCB KIT RS232+USB 2port','3')
Insert Into Product Values('Thermal Printer Main Board PCB KIT RS232+USB+LAN 3port','3')
Insert Into Product Values('Bar Code Scanner X Print X-9300/x500','3')
Insert Into Product Values('Barcode Stand','3')
Insert Into Product Values('Remax Bluetooth Handsfree T8 Black','4')
Insert Into Product Values('Remax Bluetooth Handsfree T8 White','4')
Insert Into Product Values('LG Tone HBS 900 Bluetooth Wireless Handsfree','4')
Insert Into Product Values('LG TONE HBS 730 Bluetooth wireless Handsfree','4')
Insert Into Product Values('Power Beats3 Bluetooth wireless handsfree','4')
Insert Into Product Values('LG TONE ultra HBS 800 bluetooth handsfree','4')
Insert Into Product Values('Remax Bluetooth Handsfree RB T3','4')
Insert Into Product Values('Remax Bluetooth Handsfree RB T5','4')
Insert Into Product Values('Remax Bluetooth Handsfree RBT7','4')
Insert Into Product Values('Ur beats wireless bluetooth handsfree 4.3','4')
Insert Into Product Values('Remax T9 Bluetooth Headset','4')
Insert Into Product Values('MI BLUETOOTH HEADSET','4')
Insert Into Product Values('REMAX BLEUTOOTH HEADSET T10','4')
Insert Into Product Values('Remax S2 Magnet Sports Bluetooth Handsfree','4')
Insert Into Product Values('Remax S8 Neckband Sport earphones Bluetooth handsfree','4')
Insert Into Product Values('Remax Bluetoot Handsfree T13','4')
Insert Into Product Values('TWIN TRUE BLUETOOTH EARPHONE V4.2+DER H9Q I7','4')
Insert Into Product Values('BASEUS BLUETOOTH EARPHONE NGA01','4')
Insert Into Product Values('Baseus Encok Mini Wireless Earphone NGA02','4')
Insert Into Product Values('BASEUS Magnet Bluetooth HANDFREE NGB11','4')
Insert Into Product Values('Twin True Wireless Earphone V4.2+DER H9Q I7s','4')
Insert Into Product Values('Twin True Wireless Earphone IP8','4')
Insert Into Product Values('Beats Bluetooth Wireless Studio Headphone TM010','5')
Insert Into Product Values('Nia Q1 bluetooth wireless headphone','5')
Insert Into Product Values('NIA X2 Bluetooth wireless headphone Black','5')
Insert Into Product Values('Beats Bluetooth Headphone TM019','5')
Insert Into Product Values('Bluedio Bluetooth Headset H+','5')
Insert Into Product Values('Bluedio Bluetooth Headset T2+','5')
Insert Into Product Values('JBL Bluetooth Headset S990','5')
Insert Into Product Values('JBL QUIETCOMFORR BLUETOOTH HEADSET QC35','5')
Insert Into Product Values('BOSE QUIETCOMFORT BLUETOOTH HEADSET QC950','5')
Insert Into Product Values('Remax Bluetooth Headphone 195HB','5')
Insert Into Product Values('Sony Bluetooth Headphones SBH60','5')
Insert Into Product Values('NIA X5SP bluetooth wireless headphone+speaker','5')
Insert Into Product Values('Beats Bluetooth Wireless Studio 3 Headphone','5')
Insert Into Product Values('BEATS BLUETOOTH WIRELESS SOLO3 HEADPHONE','5')
Insert Into Product Values('Bose SoundlLink Mini Boluetooth Wireless Speaker small box','6')
Insert Into Product Values('Beats Pill Bluetooth Wireless Speaker TF','6')
Insert Into Product Values('Bose Bluetooth Touch Speaker BE8','6')
Insert Into Product Values('JBL Charge2+ Bluetooth Speaker','6')
Insert Into Product Values('ROCK BLUETOOTH SPEAKER B15','6')
Insert Into Product Values('JBL Charge3+ Bluetooth Speaker','6')
Insert Into Product Values('Bose Soundlink 2+ Bluetooth Wireless Speaker','6')
Insert Into Product Values('Rock HFQ6S Bluetooth Wireless Speaker','6')
Insert Into Product Values('Remax Bluetooth Speaker RBM13','6')
Insert Into Product Values('AERO BULL BLUETOOTH SPEAKER','6')
Insert Into Product Values('Blutooth speakers portable Bs 131','6')
Insert Into Product Values('JBL BS03 Bluetooth Speaker Round','6')
Insert Into Product Values('Havit Me Bluetooth Wireless Speaker','6')
Insert Into Product Values('DANIU Bluetooth Light Speaker','6')
Insert Into Product Values('JBL K6+ BLUEOOTH SPEAKER','6')
Insert Into Product Values('JBL CHARGE MINI 3+ BLUETOOTH SPEAKER','6')
Insert Into Product Values('Romoss sense 4p 10400Mah Power bank for smart phones','7')
Insert Into Product Values('Romoss Sense 6p 20000Mah Power bank for smart phones','7')
Insert Into Product Values('Romoss Sense 9  25000MAH Power Bank for Smart Phones','7')
Insert Into Product Values('Mi Power Bank 2 10000Mah with 2USB  (Black)','7')
Insert Into Product Values('MI POWER BANK 2C 20000mah','7')
Insert Into Product Values('ASPOR POWER BANK 6000MAH POLYMER AIR ULTRA THIN  A373','7')
Insert Into Product Values('ASPOR POWER BANK 10000MAH POLYMER AIR ULTRA THIN  A383','7')
Insert Into Product Values('Mi Power Bank 2 10000Mah with 2USB  (Silver)','7')
Insert Into Product Values('ASPOR POWER BANK 10000MAH POLYMER AIR Q388 FAST CHARGING 3.0 (Black)','7')
Insert Into Product Values('Romoss Rt10 Pro Power bank 10000 Mah Qualcomm 3.0 Fast Charging','7')
Insert Into Product Values('ASPOR POWER BANK 10000MAH POLYMER AIR Q388 FAST CHARGING 3.0 (Silver)','7')
Insert Into Product Values('Android and PC USB Endoscope Cam 3.5M','8')
Insert Into Product Values('Remax Car Dashboard Camera CX01 (1080p)','8')
Insert Into Product Values('IP wireless Camera 360 with 2 antenna','8')
Insert Into Product Values('Action Sports Camera WiFi 4K','8')
Insert Into Product Values('Car DVR Mirror DUAL Camera Front/Back 1080p','8')
Insert Into Product Values('IP WIRELSS PANORAMIC FISH CAMERA V380','8')
Insert Into Product Values('Car DVR mirror 7 inch LCD Touch Screen Front and Back camera 1080p','8')
Insert Into Product Values('IP wirless 3D navigation IPC360 panoramic camera 1080P','8')
Insert Into Product Values('IP WIRLESS BULLET CAMERA WATERPROOF 8110','8')
Insert Into Product Values('Doorbell IP wirless with Camera ios and Andriod ','8')
Insert Into Product Values('Android Smart watch DZ09 Black','9')
Insert Into Product Values('Android Smart watch DZ09 Golden','9')
Insert Into Product Values('Android Smart watch W08 Black','9')
Insert Into Product Values('Android Smart watch W08 White','9')
Insert Into Product Values('Android Smart watch GT08 Black','9')
Insert Into Product Values('Mi Band 2','9')
Insert Into Product Values('Android Smart watch GT08 Silver','9')
Insert Into Product Values('GPS WATCH GSM WITH WIFI Q90','9')
Insert Into Product Values('Android Smart watch GT08 Plus with WiFi and 3G 4.4 kitkat','9')
Insert Into Product Values('Android Smart Watch X01 with WiFi and 3G 4.4 kitkat','9')
Insert Into Product Values('Smart Watch Y1 with GSM slot for iOS and Android with camera ','9')
Insert Into Product Values('SMART WATCH BATTERY X01','9')
Insert Into Product Values('SMART WATCH BATTERY DZ09','9')
Insert Into Product Values('Smart Health Watch 115hr','9')
Insert Into Product Values('Smart Health Bracelet Sprots K1 Black','9')
Insert Into Product Values('Smart Health Bracelet Sprots K1 Blue','9')
Insert Into Product Values('Smart Watch Battery Z50','9')
Insert Into Product Values('Android Smart Watch X02s lolipop 5.1 with WiFi and 3G','9')
Insert Into Product Values('SPORT B.P HEART RATE MONITOR Y07S HELTH BAND (Black)','9')
Insert Into Product Values('USB Hub 3.0 4 port Power+Magnet Hub U307 IE Top Black','10')
Insert Into Product Values('USB 3.0 Hub 4 Port U313 IE Top  Black','10')
Insert Into Product Values('USB Hub 3.0 4 Port 303','10')
Insert Into Product Values('USB HUB 7 PORT 2.0 WITH SWITCH','10')
Insert Into Product Values('USB FAST CHARGER 12 PORT 12AMP W858','10')
Insert Into Product Values('USB HUB 2.0 4 Port Power+Magnet Hub U207 IE Top Black','10')
Insert Into Product Values('USB hub 4 port 2.0 with Button','10')
Insert Into Product Values('USB hub charger Remax 5 port 5V 6A RUU1','10')
Insert Into Product Values('USB HUB 7 PORT 3.0 WITH SWITCH','10')
Insert Into Product Values('ORICO USB HUB 4PORT 3.0 W59-U3-303-BK-PRO','10')
